EXPERIMENT_DATA_COLUMN = 'Experiment Data'
FEED_VOLUME_COLUMN = 'Feed Volume (mL)'
CONC_BEFOROE_FEED_COLUMN = 'Concentration Before Feeding'
CONC_AFTER_FEED_COLUMN = 'Concentration After Feeding'
MEASURED_CUMULATIVE_COLUMN = 'Calculated Cumulative Concentration'
CUMULATIVE_CONC_COLUMN = 'Cumulative Consumption/Production'
SP_RATE_COLUMN = 'SP. Rate Two-Point Calculation'
SP_RATE_POLY_COLUMN = 'SP. Rate Polynomial Regression'
SP_RATE_ROLLING_COLUMN = 'SP. Rate Rolling Window Polynomial Regression'

DATE_COLUMN = 'Date (MM/DD/YY H:MM:SS AM/PM)'
CELL_LINE_COLUMN = 'Cell Line'
ID_COLUMN = 'ID' 
NAME_COLUMN = 'Name'
